python3 embedGO.py \
       -dim 100 \
       -lr 0.12 \
       -epochs 1000 \
       -negs 50 \
       -batchsize 50 \
       -burnin 20 \
       -gpu 0 \
       -manifold poincare \
       -dset data/HPOfull_train.tsv \
       -checkpoint result/HPOfull_d100_lr40.pth \
       -fresh \
       -sparse
